import type { INodeProperties } from 'n8n-workflow';

import {
	createPaginationFields,
	createStringListField,
	groupJidSelect,
	showFor,
} from '../../shared/descriptions';

export const groupDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: showFor('group'),
		options: [
			{ name: 'Accept Group Invite', value: 'acceptInvite', action: 'Accept group invite' },
			{
				name: 'Add Group Participants',
				value: 'addParticipants',
				action: 'Add participants to group',
			},
			{ name: 'Create Group', value: 'create', action: 'Create group' },
			{ name: 'Get Group Picture', value: 'getPicture', action: 'Get group profile picture' },
			{ name: 'Get Invite Info', value: 'getInviteInfo', action: 'Get group invite info' },
			{ name: 'Get Invite Link', value: 'getInviteLink', action: 'Get group invite link' },
			{ name: 'Get Many', value: 'getAll', action: 'Get many groups' },
			{ name: 'Get Metadata', value: 'getMetadata', action: 'Get group metadata' },
			{ name: 'Get Participants', value: 'getParticipants', action: 'Get group participants' },
			{ name: 'Leave Group', value: 'leave', action: 'Leave group' },
			{
				name: 'Remove Group Participants',
				value: 'removeParticipants',
				action: 'Remove participants from group',
			},
			{
				name: 'Update Group Participants',
				value: 'updateParticipants',
				action: 'Promote or demote group participants',
			},
			{ name: 'Update Group Settings', value: 'updateSettings', action: 'Update group settings' },
		],
		default: 'getAll',
	},
	...createPaginationFields('group', ['getAll']),
	{
		...groupJidSelect,
		displayOptions: showFor('group', [
			'getMetadata',
			'getParticipants',
			'addParticipants',
			'removeParticipants',
			'updateParticipants',
			'updateSettings',
			'getPicture',
			'getInviteLink',
			'leave',
		]),
	},
	{
		displayName: 'Group Name',
		name: 'groupName',
		type: 'string',
		default: '',
		required: true,
		displayOptions: showFor('group', ['create']),
	},
	createStringListField(
		'Participants',
		'participants',
		'group',
		['create', 'addParticipants', 'removeParticipants', 'updateParticipants'],
		'Participant',
		'Participant JID',
		'1234567890@s.whatsapp.net',
	),
	{
		displayName: 'Action',
		name: 'participantAction',
		type: 'options',
		options: [
			{ name: 'Promote', value: 'promote' },
			{ name: 'Demote', value: 'demote' },
		],
		default: 'promote',
		displayOptions: showFor('group', ['updateParticipants']),
	},
	{
		displayName: 'Settings',
		name: 'settings',
		type: 'collection',
		placeholder: 'Add Setting',
		default: {},
		displayOptions: showFor('group', ['updateSettings']),
		options: [
			{
				displayName: 'Announce',
				name: 'announce',
				type: 'boolean',
				default: false,
				description: 'Whether only admins can send messages',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Join Approval',
				name: 'joinApproval',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Member Add',
				name: 'memberAdd',
				type: 'boolean',
				default: false,
			},
			{
				displayName: 'Restrict',
				name: 'restrict',
				type: 'boolean',
				default: false,
				description: 'Whether only admins can edit group info',
			},
			{
				displayName: 'Subject',
				name: 'subject',
				type: 'string',
				default: '',
			},
		],
	},
	{
		displayName: 'Invite Code',
		name: 'inviteCode',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'ABCDE12345',
		displayOptions: showFor('group', ['getInviteInfo', 'acceptInvite']),
	},
];
