import type { INodeProperties } from 'n8n-workflow';

import { createStringListField, showFor } from '../../shared/descriptions';

const sendOperations = [
	'sendText',
	'sendImage',
	'sendVideo',
	'sendDocument',
	'sendAudio',
	'sendSticker',
	'sendContact',
	'sendLocation',
	'sendPoll',
];

export const messageDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: showFor('message'),
		options: [
			{
				name: 'Decrypt Webhook Media',
				value: 'decryptMedia',
				action: 'Decrypt webhook media to binary',
			},
			{ name: 'Delete Message', value: 'delete', action: 'Delete sent message' },
			{ name: 'Edit Message', value: 'edit', action: 'Edit sent message' },
			{ name: 'Get Message Info', value: 'getInfo', action: 'Get message delivery info' },
			{ name: 'Mark as Read', value: 'markAsRead', action: 'Mark message as read' },
			{ name: 'Resend Message', value: 'resend', action: 'Resend failed message' },
			{ name: 'Send Audio', value: 'sendAudio', action: 'Send audio message' },
			{ name: 'Send Contact', value: 'sendContact', action: 'Send contact card' },
			{ name: 'Send Document', value: 'sendDocument', action: 'Send document message' },
			{ name: 'Send Image', value: 'sendImage', action: 'Send image message' },
			{ name: 'Send Location', value: 'sendLocation', action: 'Send location message' },
			{ name: 'Send Poll', value: 'sendPoll', action: 'Send poll message' },
			{ name: 'Send Sticker', value: 'sendSticker', action: 'Send sticker message' },
			{ name: 'Send Text', value: 'sendText', action: 'Send text message' },
			{ name: 'Send Video', value: 'sendVideo', action: 'Send video message' },
			{ name: 'Upload Media File', value: 'uploadMedia', action: 'Upload media file' },
		],
		default: 'sendText',
	},
	{
		displayName: 'Recipient',
		name: 'to',
		type: 'string',
		default: '',
		required: true,
		placeholder: '+1234567789 or 123456789-987654321@g.us',
		description: 'Supports phone numbers, group JIDs, and channel JIDs',
		displayOptions: showFor('message', sendOperations),
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		typeOptions: {
			rows: 4,
		},
		default: '',
		displayOptions: showFor('message', [
			'sendText',
			'sendImage',
			'sendVideo',
			'sendDocument',
			'sendAudio',
			'sendSticker',
			'sendLocation',
		]),
	},
	{
		displayName: 'Image URL',
		name: 'imageUrl',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'https://example.com/image.jpg',
		displayOptions: showFor('message', ['sendImage']),
	},
	{
		displayName: 'Video URL',
		name: 'videoUrl',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'https://example.com/video.mp4',
		displayOptions: showFor('message', ['sendVideo']),
	},
	{
		displayName: 'Document URL',
		name: 'documentUrl',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'https://example.com/report.pdf',
		displayOptions: showFor('message', ['sendDocument']),
	},
	{
		displayName: 'File Name',
		name: 'fileName',
		type: 'string',
		default: '',
		placeholder: 'report-2026.pdf',
		displayOptions: showFor('message', ['sendDocument']),
	},
	{
		displayName: 'Audio URL',
		name: 'audioUrl',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'https://example.com/audio.mp3',
		displayOptions: showFor('message', ['sendAudio']),
	},
	{
		displayName: 'Sticker URL',
		name: 'stickerUrl',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'https://example.com/sticker.webp',
		displayOptions: showFor('message', ['sendSticker']),
	},
	{
		displayName: 'View Once',
		name: 'viewOnce',
		type: 'boolean',
		default: false,
		displayOptions: showFor('message', ['sendImage', 'sendVideo', 'sendAudio']),
	},
	{
		displayName: 'Message Options',
		name: 'messageOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: showFor('message', sendOperations),
		options: [
			{
				displayName: 'Reply To Message ID',
				name: 'replyTo',
				type: 'number',
				typeOptions: {
					minValue: 1,
				},
				default: 1,
			},
		],
	},
	createStringListField(
		'Mentions',
		'mentions',
		'message',
		['sendText', 'sendImage', 'sendVideo', 'sendDocument', 'sendAudio', 'sendSticker'],
		'Mention',
		'Participant JID',
		'1234567890@s.whatsapp.net',
		'Use for group messages that mention specific members',
	),
	{
		displayName: 'Contact Name',
		name: 'contactName',
		type: 'string',
		default: '',
		required: true,
		displayOptions: showFor('message', ['sendContact']),
	},
	{
		displayName: 'Contact Phone',
		name: 'contactPhone',
		type: 'string',
		default: '',
		required: true,
		placeholder: '+1234567789',
		displayOptions: showFor('message', ['sendContact']),
	},
	{
		displayName: 'Latitude',
		name: 'latitude',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: showFor('message', ['sendLocation']),
	},
	{
		displayName: 'Longitude',
		name: 'longitude',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: showFor('message', ['sendLocation']),
	},
	{
		displayName: 'Location Name',
		name: 'locationName',
		type: 'string',
		default: '',
		displayOptions: showFor('message', ['sendLocation']),
	},
	{
		displayName: 'Address',
		name: 'address',
		type: 'string',
		default: '',
		displayOptions: showFor('message', ['sendLocation']),
	},
	{
		displayName: 'Question',
		name: 'pollQuestion',
		type: 'string',
		default: '',
		required: true,
		displayOptions: showFor('message', ['sendPoll']),
	},
	{
		displayName: 'Allow Multiple Answers',
		name: 'pollMultiSelect',
		type: 'boolean',
		default: false,
		displayOptions: showFor('message', ['sendPoll']),
	},
	createStringListField(
		'Options',
		'pollOptions',
		'message',
		['sendPoll'],
		'Option',
		'Value',
		'Blue',
	),
	{
		displayName: 'Upload Payload',
		name: 'uploadPayload',
		type: 'json',
		default: '{"base64": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUg..."}',
		description: 'Provide either a Data URL or a base64 string with an optional mimetype field',
		displayOptions: showFor('message', ['uploadMedia']),
	},
	{
		displayName: 'Payload Source',
		name: 'decryptPayloadSource',
		type: 'options',
		options: [
			{
				name: 'Automatic',
				value: 'auto',
				description: 'Use the incoming item JSON automatically',
			},
			{
				name: 'Manual JSON',
				value: 'manual',
				description: 'Paste a webhook payload manually',
			},
		],
		default: 'auto',
		description:
			'Automatic is the easiest option. Just connect the webhook or trigger output to this node and it will use that item JSON.',
		displayOptions: showFor('message', ['decryptMedia']),
	},
	{
		displayName: 'Webhook Payload',
		name: 'decryptPayload',
		type: 'json',
		default: '',
		description:
			'Only needed in Manual JSON mode. You can paste the full WasenderAPI webhook payload or just the data.messages value.',
		displayOptions: {
			show: {
				resource: ['message'],
				operation: ['decryptMedia'],
				decryptPayloadSource: ['manual'],
			},
		},
	},
	{
		displayName: 'Message ID',
		name: 'msgId',
		type: 'number',
		typeOptions: {
			minValue: 1,
		},
		default: 0,
		required: true,
		displayOptions: showFor('message', ['getInfo', 'edit', 'delete', 'resend']),
	},
	{
		displayName: 'New Text',
		name: 'newText',
		type: 'string',
		typeOptions: {
			rows: 4,
		},
		default: '',
		required: true,
		displayOptions: showFor('message', ['edit']),
	},
	{
		displayName: 'Message Key',
		name: 'messageKey',
		type: 'json',
		default: '{"id":"3EB06A5E244031B4A5D1","remoteJid":"1234567890@s.whatsapp.net","fromMe":false}',
		displayOptions: showFor('message', ['markAsRead']),
	},
];
